### PR TITLE
fix: add handler for GeocoderUnavailable error

### PR DESCRIPTION
**Pull request by Auch-Auch**
Sometimes geocoder is unavailable for some reason, some strings are not valid for him, apparently

### CODE REVIEW

**Comment by lemontree210** [comment]
> some strings are not valid for him, apparently

could you find any specifics?

**Comment by Auch-Auch** [comment]
GM+, for example

**Comment by lemontree210** [comment]
> GM+, for example

GM+ doesn't look like a valid string for me either :)

**Comment by Auch-Auch** [comment]
Yes, but it used to worked so API changed apparently

**Comment by Auch-Auch** [comment]
I mean in this case it should not throw that exception but return None or some other exception since not city is found

**Review by lemontree210 — APPROVED** [review]

**Pull request merged**
